aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'エンタープライズのためのフルマネージド型のセキュアな文書保存と共有サービス。ユーザーは好みのデバイスから、いつでもどこでもクラウド上に保存されているファイルにアクセスし、表示してフィードバックを残すことができる。当初はAmazon ゾカロという名称で発表された。   ' AmazonWorkDocs.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'エンタープライズのためのフルマネージド型のセキュアなメールおよびカレンダーサービス。既存の Active ディレクトリーやAWS ディレクトリー Serviceでユーザ情報を管理することも可能。Microsoft Outlook、Webブラウザ、iOS および Android ネイティブの Eメールアプリケーションを使用して、E メール、連絡先、カレンダーにシームレスにアクセスできる。  ' AmazonWorkMail.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'クラウドで実現されるデスクトップコンピューティング。PC、スマートフォン、タブレットなどあらゆるデバイスからアクセス可能で、すべてのデバイスで同期する。ユーザディスク領域は、定期的にS3にバックアップされる。 ' AmazonWorkSpaces.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'ECツーおよびS3を利用してホストされる Hadoopクラスタフレームワークのサービス。莫大な量のデータ処理を、簡単に、費用対効果が高く、利用することができる  ' Analytics_AmazonEMR.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'Elasticsearchクラスターを簡単にデプロイ、操作、スケーリングできるようにするマネージドサービス。' Analytics_AmazonElasticsearch.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text '予測アプリケーションを構築できる機械サービス。既存データからパターンを発見し、新しいデータから予測を生成する。 ' Analytics_AmazonMachineLearning.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'SPICE エンジンを活用したビジネスインテリジェンス (BI) サービス。可視化の構築、アドホック分析の実行およびデータからビジネスインサイトを迅速に得ることを容易とする。 ' Analytics_AmazonQuickSight.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'AWSの各サービス、ならびにオンプレミスのデータソース間を、指定された間隔で、データ処理やデータ移動ができる、データドリブンなオーケストレーションサービス。  ' Analytics_DataPipeline.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'ビッグデータのリアルタイム・ストリームを扱うために設計されたマネージドサービス。大規模でリアルタイムなデータ投入と処理が必要とされる、あらゆる場面で使うことができる。 -Amazon Kinesis</p>' Analytics_Kinesis.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'API の配布、保守、監視、保護が行える、全面的に管理されたサービス。バックエンドからのデータ、ビジネスロジック、機能にアクセスする、アプリケーションの玄関として振る舞う API を作成できる。  ' ApplicationServices_APIGateway.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'フルマネージド型の「検索サービス」。高速で拡張性に優れた検索機能をアプリケーションに容易に統合できる。- Amazon CloudSearch</p>' ApplicationServices_AmazonCloudSearch.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text '高度なスケーラビリティ、使いやすさ、経済性を実現するクラウドの音声・動画変換サービス。音声・動画ファイルをスマートフォン、タブレット、PC などのデバイスで再生可能なバージョンに変換できる。音声のみのストリームを作成するために、ビデオファイルから音声を抜き出すこともできる。 ' ApplicationServices_AmazonElasticTranscoder.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text '年間10億通を送ると言われているAmazon.comが培ったEメールインフラストラクチャのノウハウを利用することができる、非常に拡張性が高くコスト効率の良い大量Eメール送信サービス 。 ' ApplicationServices_AmazonSES.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'AWSで一番最初にリリースされたサービスで、コンピュータ間でメッセージを移動する際に、それらを格納するための、信頼性の高い、拡張性のある、キューサービス。 ' ApplicationServices_AmazonSQS.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'フルマネージド型の拡張性と耐障害性に優れたアプリケーションを構築するためのワークフローサービス。1つのアプリケーションを構成するさまざまな処理ステップを「タスク」として作成することにより、分散アプリケーションの作業を実行することができる。' ApplicationServices_AmazonSWF.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'クラウド上から高品質でリッチな画像を使ったアプリケーションのストリーミングを可能にする。  ' ApplicationServices_AppStream.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'クラウド内で規模の変更が可能なコンピュータ処理能力を提供するウェブサービス。管理者アクセスが可能な仮想マシンとして提供される。  ' Compute_AmazonEC2.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'Docker コンテナイメージを簡単に保存、管理、デプロイできる完全マネージド型の Docker コンテナレジストリ。 Amazon ECツー Container Service (ECS) に統合されている。 ' Compute_AmazonEC2ContainerRegistry.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'Docker コンテナをサポートするコンテナ管理サービス。Amazon ECツー インスタンスのマネージド型クラスターでのアプリケーションの実行を容易にする。 ' Compute_AmazonEC2ContainerService.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text '仮想インスタンスの起動イメージとして、OSやソフトウェアが保存されています。 ' Compute_AmazonEC2_AMI.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'gitやIDEを使い、AWSクラウド上に、アプリケーション実行環境を迅速に、簡単にデプロイするためのサービス。' Compute_ElasticBeanstalk.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text '受信アプリケーショントラフィックを複数の Amazon ECツー インスタンス間で、自動的に分散。アプリケーションの耐障害性を実現し、アプリケーショントラフィックのルーティングに必要な負荷分散能力をシームレスに提供。 ' Compute_ElasticLoadBalancing.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'ECツーインスタンスの準備をせずに、クラウド上でアプリケーションをビルドして実行するための、管理不要なコンピューティングプラットフォーム。S3やKinesis、DynamoDBのイベントをトリガーに、ユーザーが用意したコードを自動的に実行する。 ' Compute_Lambda.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'Oracle から Oracle のような同種のデータベース間の移行や、Oracle から Amazon Aurora または Microsoft SQL から MySQL といった異なるデータベースプラットフォーム間のデータ移行ツール。 ' Database_AWSDatabaseMigrationService.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'データアクセスをメモリ上にキャッシュすることでアプリケーションのパフォーマンスを向上させる memcached や Redis に準拠しているキャッシュサービス。 ' Database_AmazonElasticCache.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'フルマネージド型のRDBMSサービス。必要に応じてコンピュートリソースやストレージ容量を拡張できる柔軟性や、煩わしい管理作業を軽減する自動バックアップやパッチ当て機能により、利用者はアプリケーションの開発やビジネスに集中できる。マイエスキューエル、Oracle Database、SQLServer、PostgreSQLが利用できる。' Database_AmazonRDS.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'フルマネージド型のデータウェアハウスサービス。クラスター構成を用いて、ペタバイト級のデータセットに対して高いクエリ性能を実現する。  ' Database_AmazonRedShift.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'EBSの増分バックアップをS3上に保存します。データを新しい EBS ボリュームに復元するために必要な情報がすべて含まれます。 ' StorageContentDelivery_snapshot.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'フルマネージド型の NoSQL データベースサービス。秒間の読み書き性能を「ユニット」という単位で指定でき、必要に応じていつでも変更することができる。  ' Database_DynamoDB.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text '企業が安全で高度にスケーラブルなプライベート Git リポジトリをホストすることを容易にする、完全マネージド型のソース管理サービス。 ' DeploymentManagement_AWSCodeCommit.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'ECツー インスタンスへのコードのデプロイメント、アップデートを自動化するサービスで、アプリケーションの複雑なアップデート処理、デプロイ中のダウンタイムの回避、新規機能の迅速なリリースを容易に行なうことを可能とする。  ' DeploymentManagement_CodeDeploy.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text '迅速で信頼性の高いアプリケーションのアップデートを可能にする継続的デリバリーサービス。コードが変更されるたびに、定義したリリースプロセスモデルに基づいて、コードを構築、テスト、デプロイができる。 ' DeploymentManagement_CodePipeline.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text '接続されたデバイスが簡単かつ安全にクラウドアプリケーションやその他のデバイスとやり取りできるマネージド型クラウドプラットフォーム。数十億のデバイスと数兆のメッセージをAWSエンドポイントおよび他のデバイスに確実かつ安全に処理しルーティングする。 ' InternetOfThings_AWS-IOT.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'テンプレートを利用することで、AWSのインフラやリソースを集約し、スタックとしてデプロイすることができるサービス。　 ' ManagementTools_CloudFormation.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'AWS APIに対するコールを記録し、指定したS3バケットにログファイルを保存することができる機能。ログファイルが保存されるたびに、Amazon SNSのトピックに通知を送ることができる。  ' ManagementTools_CloudTrail.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'AWSクラウドのリソースと、AWS上で実行するアプリケーションをモニタリングできるサービス。利用料金の監視もできる。 ' ManagementTools_CloudWatch.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'AWSが提供する様々なサービスの構成管理、履歴管理を実現するサービス。AWS上にある構成アイテムのリソース変更状況をS3上にログとして記録して、リソースの構成変更履歴を時系列で参照することができる。 ' ManagementTools_Config.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'Chefレシピを利用して設定が可能なデブオプスソリューションサービス。各種リソースをレイヤーという論理的なモデルで管理する。  ' ManagementTools_OpsWorks.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'モバイルアプリケーションを構築するための新しいコンソール。ユーザー認証、データストレージ、バックエンドのロジック、プッシュ通知、コンテンツ配信、および分析などの機能をアプリケーションを構築できる。  ' MobileServices_AWSMobileHub.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'ユーザー認証機能だけでなく、データ同期に関する機能を提供するシンプルなサービスで、モバイルデバイス間でユーザーのアプリケーションデータを安全に管理また同期するのに役立つ。 ' MobileServices_Cognito.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'Android、iOS および Fire OS アプリケーションのテストサービス。 ' MobileServices_DeviceFarm.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'アプリケーションの使用状況データを簡単かつ費用対効果に優れた方法で収集、分析できるようにするサービス。収集したデータはマネジメントコンソールから確認だけでなくS3やRedshiftへ自動で出力することができる。モバイルアプリケーションのDAU、MAU、セッション数などだけでなくカスタムイベントも取得することもできる。 ' MobileServices_MobileAnalytics.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'HTTP通知やEメール通知、SMS通知やAmazon SQSへの通知ができるサービス。アプリケーションからアプリケーション、人へのメッセージの迅速な配信環境を実現できる。 ' MobileServices_SNS.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'ユーザとAWSのネットワークを専用線で接続するためのサービス。 ' Networking_AWSDirectConnect.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'AWSインフラ内に、仮想ネットワーク環境として、ユーザが制御可能な閉域網を構築できるサービス。 ' Networking_AmazonVPC.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text '稼働率100%のサービスレベルアグリーメントが適用されているDNSサービス。 ' Networking_Route53.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text '安全なキー管理に対する米国政府標準規格に適合するように設計/検証されたハードウェアセキュリティモジュールで暗号キーを保護することができる。' SecurityIdentity_CloudHSM.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Takumi --region us-west-2  --text 'AWS リソースを既存のオンプレミス Microsoft アクティブ ディレクトリー で接続したり、AWS クラウド上に新しいスタンドアロンなディレクトリをセットアップしたりできる管理型サービス。 ' SecurityIdentity_DirectoryService.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text 'AWSサービスおよびリソースへのアクセスを安全にコントロールするために、ユーザーとグループを作成および管理し、アクセス権を使用して AWSリソースへのアクセスを許可および拒否できる仕組み。 ' SecurityIdentity_IdentityAccessManagement.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text 'データの暗号化に使用する暗号化キーを簡単に作成および管理できるマネージドサービス。 ' SecurityIdentity_KeyManagementService.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text 'IT管理者が内部のユーザに対して、一貫性と統制を管理された形でAWS上のサービスを提供するためのツール。管理者は、各アプリケーションまたは AWS リソースにアクセスできるユーザーを制御して、組織のビジネスポリシーへのコンプライアンスを実施できる。 ' ManagementTools_ServiceCatalog.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text 'ユーザーのAWS 環境を検査し、コスト削減、システムパフォーマンス向上、セキュリティギャップの封鎖につながる推奨事項をお知らせします。コスト最適化、セキュリティ、耐障害性、パフォーマンス改善の4 つのカテゴリに分けてすばやく確認できます。 ' SecurityIdentity_TrustedAdvisor.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text '定義する条件に基づきウェブリクエストを許可、ブロック、または監視 (カウント) するルールを設定し、ウェブアプリケーションを攻撃から保護するのを助けるウェブアプリケーションファイアウォール。 ' SecurityIdentity_WebAppFirewall.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text '物理ストレージアプライアンスを使用し、インターネットを迂回して AWS との大容量データ転送を高速化するサービスです。Amazonの高速内部ネットワークを駆使し、直接ユーザー所有のストレージデバイスとのデータ転送をサポートします。' StorageContentDelivery_AWSIMportExport.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text 'エッジロケーションのグローバルなネットワークを利用し、静的コンテンツやストリーミングコンテンツを高パフォーマンスに配信をするサービス。 ' StorageContentDelivery_AmazonCloudFront.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text 'アクセス頻度の低いデータや、取り出しに数時間かかっても問題ないデータに合わせて最適化された、低コストのオンラインストレージサービス。API経由のアクセス以外に、Amazon S3と連携することで、Management Console からデータを管理することも可能である。 ' StorageContentDelivery_AmazonGlacier.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text 'いつでも、ウェブ上のどこからでも容量に関係なくデータを格納・取得できる耐久性に優れたオンライン・ストレージサービス。静的なウェブサイトのホスティングも可能。 ' StorageContentDelivery_AmazonS3.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text 'オンプレミスのIT環境やAmazon ECツーとAWSのストレージインフラをシームレスに統合する仕組み。iSCSIで接続可能な仮想ストレージを提供する。 ' StorageContentDelivery_AmazonStorageGateway.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text 'ストレージ容量を自動的に拡大および縮小できるNetwork File System バージョン4 プロトコルをサポートしたファイルストレージサービス。 ' StorageContentDelivery_EFS.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text '物理的な移動のためのセキュアなストレージアプライアンスを使用して、テラバイトからペタバイト規模のデータを AWS内外へデータ転送するソリューション。  ' StorageContentDelivery_Snowball.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text 'AWS にデプロイされたアプリケーションのセキュリティとコンプライアンスを向上させるための、自動化されたセキュリティ評価サービス。 ' Security-Identity_AmazonInspector.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text 'AWS の各種サービスで使用するSSL 証明書のプロビジョニング、管理、およびデプロイを簡単に行えるサービス。' SecurityIdentity_CertificateManager.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text 'アプリケーションの可用性を維持できると同時に、お客様が定義する条件に応じて、ECツー のキャパシティーを動的および自動的に縮小あるいは拡張できます。 ' Compute_AmazonEC2_AutoScaling.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text '使われていないECツーインスタンスに入札することでECツーを利用できます。通常スポットインスタンスはオンデマンド価格と比較して割引価格で利用できます。   ' Compute_AmazonEC2_Spotinstance.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text 'VPC内のインスタンスとインターネットとの間の通信を可能にするVPC コンポーネントであり、冗長性と高い可用性を備えており、水平スケーリングが可能です。 ' Networking_AmazonVPC_internetgateway.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text 'VPC内のインスタンスとユーザー自身のネットワークとの間の通信を可能にするVPC コンポーネントです。 ' Networking_AmazonVPC_VPNgateway.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text '2つのVPC間でトラフィックをルーティングすることを可能にするネットワーク接続です。' Networking_AmazonVPC_VPCpeering.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text 'ルート53におけるゾーン情報を定義する機能です。 ' Networking_AmazonRoute53_hostedzone.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text 'S3にオジュジェクトを保存するために作成します。名前は完全ユニークである必要があります。 ' StorageContentDelivery_AmazonS3_bucket.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text 'エンドユーザーにコンテンツをより低いレイテンシーで配信するために世界中に配置されているCloudFrontのエッジサーバーです。 ' StorageContentDelivery_AmazonCloudFront_edgelocation.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text 'ECツー インスタンスと組み合わせて使用できる、永続的なブロックストレージボリュームです。  ' StorageContentDelivery_AmazonEBS.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text '様々な認定機関からのレポートや事業提携契約、機密保持契約などの書類にオンデマンドでアクセスできる無料のセルフサービスポータル。  ' AWSArtifact.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text 'バッチジョブのコードを簡単にパッケージ化し、その依存関係を指定できるサービス。実行パラメータとジョブ依存関係を指定でき、バッチコンピューティングワークフローでよく使用されるさまざまなエンジンや言語 (Pegasus WMS、Luigi、AWS Step Functions など) との統合を簡単に行うことができる。 ' AWSBatch.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text 'オンプレミスのデータセンターで実行されているアプリケーション、関連する依存関係を検出するサービス。  ' AWSApplicationDiscoveryService.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text '完全マネージド型のビルドサービス。ビルドサーバーのプロビジョニング、管理、スケーリングが不要。スケーリングは継続的に行われ、複数のビルドが同時に実行される。   ' AWSCodeBuild.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text '接続されたデバイスでローカルのコンピューティング、メッセージング、およびデータキャッシュを安全に実行できるようにするソフトウェア。接続されたデバイスで AWS Lambda 関数を実行し、デバイスデータを常に同期させ、他のデバイスと安全に通信できる。   ' AWSGreengrass.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text 'ITILフレームワークに基づいて、AWSの運用管理が行えるサービス。主に大企業向け。   ' AWSManagedServices.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text '複数のアカウントを一元的に管理でき、セキュリティと自動化の設定管理が簡単になるサービス。それぞれのアカウントから利用できる AWS のサービスを管理でき、新規アカウント作成の自動化や請求の簡素化もできる。   ' AWSOrganizations.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text 'オンプレミスワークロードを従来よりも簡単に、かつ短時間で AWS に移行できるエージェントレスサービス。ライブサーバーのボリュームの増分レプリケーションを自動化、スケジュール設定、追跡できるため、大規模なサーバーの移行を簡単に処理することができる。   ' AWSServerMigrationService.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text 'マネージド型の分散サービス妨害 (DDoS) に対する保護サービスで、AWS で実行しているウェブアプリケーションを保護。アプリケーションのダウンタイムとレイテンシーを最小限に抑える常時稼働の検出と自動インライン緩和策を提供しているため、DDoS 保護のメリットを受けるために AWS サポートに従事する必要がない。 ' AWSShield.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text '視覚的なワークフローを使用して分散アプリケーションとマイクロサービスのコンポーネントを簡単に調整できるサービス。複数のステップからなるアプリケーションをシンプルに構築および実行できるようになる。 ' AWSStepFunctions.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text '製品や分散アプリケーションの分析およびデバッグを行うサービス。開発中か本番環境かにかかわらず、3 層のシンプルなアプリケーションから数千のサービスで構成される複雑なマイクロサービスアプリケーションまで、さまざまなアプリケーションを分析できる。   ' AWSX-Ray.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text 'インタラクティブなクエリサービスで、Amazon S3 内のデータを標準的な SQL を使用して簡単に分析できる。  ' AmazonAthena.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text 'セッションベースのマルチプレイヤーゲーム専用のゲームサーバーをデプロイ、運用、スケーリングするためのマネージドサービス。サーバーインフラストラクチャの管理、キャパシティーのスケールによるレイテンシーとコストの削減、利用可能なゲームセッションへのプレイヤーの適合、分散サービス妨害 (DDoS) 攻撃からの防御が簡単になる。   ' AmazonGameLift.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text '音声やテキストを使用した会話型インターフェイスをさまざまなアプリケーションに構築するためのサービス。自動音声認識 (ASR) という音声をテキストに変換するための高度な深層学習機能と、テキストの意図を理解するための自然言語理解 (NLU) を利用でき、非常に魅力的なサービスと生き生きとした音声対話を実現するアプリケーションを構築できる。  ' AmazonLex.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text '数回クリックしてメニューから設定を選択し、SSDベースのストレージ、DNS管理、固定IPが事前設定された仮想マシンを起動することができるVPSサービス。 ' AmazonLightsail.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text 'モバイルアプリケーション向けのターゲットプッシュ通知サービス。ユーザーの行動を把握し、ターゲットにするユーザーや送信するメッセージを決定し、メッセージを配信する最適な時間を計画し、キャンペーン開始後にキャンペーンの結果を追跡。   ' AmazonPinpoint.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text '文章をリアルな音声に変換するサービス。会話機能を搭載したアプリケーションを作成し、音声に対応したまったく新しいカテゴリの製品を構築することが可能。  ' AmazonPolly.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text '画像の分析をアプリケーションに簡単に追加できるようにするサービス。APIで深層学習に基づく高度な視覚検索やイメージ分析をアプリケーションにすばやく組み込むことができる。  ' AmazonRekognition.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text '簡単でセキュアなオンラインミーティング用のサービスです。  ' AmazonChime.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text '機械学習によって AWS 内の機密データを自動的に検出、分類、保護するセキュリティサービスです。 個人情報 や知的財産などの機密データが認識されます。   ' AmazonMacie.mp3
aws polly synthesize-speech  --output-format mp3  --voice-id Mizuki --region us-west-2  --text 'クラウド型カスタマーコンタクトセンターサービスです。 わずか数分でセットアップでき、サービスの設定もセルフサービス型のグラフィカルインターフェイスを使って簡単にできます。  ' AmzonConnect.mp3
